module.exports = {
  CREATE_USER: 'CREATE_USER',

  UPDATE_USER: 'UPDATE_USER',

  DELETE_USER: 'DELETE_USER',

  VIEW_USERS: 'VIEW_USERS',

  SEND_MESSAGE: 'SEND_MESSAGE',

  VIEW_ANALYTICS: 'VIEW_ANALYTICS',

  MANAGE_BILLING: 'MANAGE_BILLING',

  MANAGE_TEMPLATES: 'MANAGE_TEMPLATES',

  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
};