module.exports = {
  USER_LOGIN: 'USER_LOGIN',

  USER_LOGOUT: 'USER_LOGOUT',

  MESSAGE_SENT: 'MESSAGE_SENT',

  TEMPLATE_CREATED: 'TEMPLATE_CREATED',

  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',

  SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',
};