module.exports = {
  USER_REGISTERED: 'USER_REGISTERED',

  USER_LOGGED_IN: 'USER_LOGGED_IN',

  USER_LOGGED_OUT: 'USER_LOGGED_OUT',

  MESSAGE_SENT: 'MESSAGE_SENT',

  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',

  TEMPLATE_CREATED: 'TEMPLATE_CREATED',

  CAMPAIGN_STARTED: 'CAMPAIGN_STARTED',

  CAMPAIGN_COMPLETED: 'CAMPAIGN_COMPLETED',

  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',

  SUBSCRIPTION_CREATED: 'SUBSCRIPTION_CREATED',

  SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',
};